name = "RealmRush"
author = "codeNredstone"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e7b00a76d9403991d7aeefd90bcc80852ac69e0b10aedd04512b7b7f2d41fc8"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
