name = "RealmRush"
author = "codeNredstone"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5704aad6c30296e64c6f78c3dcd4146283a4050896a1d14e2feeb66c79cd6f1"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
