name = "GammaCraft"
author = "codeNredstone"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "334fdab88f43c2f874ddd04400f16dc4f1a5ca0adbdf36edcc4f5753e5079ccb"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
