
[origins]

	[origins."origins-classes:nitwit"]
		enabled = true

	[origins."origins:enderian"]
		enabled = true
		"origins:throw_ender_pearl" = true
		"origins:water_vulnerability" = true
		"origins:pumpkin_hate" = true
		"origins:extra_reach" = true
		"origins:ender_particles" = true
		"origins:damage_from_potions" = true

	[origins."origins:feline"]
		enabled = true
		"origins:fall_immunity" = true
		"origins:sprint_jump" = true
		"origins:velvet_paws" = true
		"origins:nine_lives" = true
		"origins:weak_arms" = true
		"origins:scare_creepers" = true
		"origins:cat_vision" = true

	[origins."origins-classes:warrior"]
		enabled = true
		"origins-classes:more_attack_damage" = true
		"origins-classes:less_shield_slowdown" = true

	[origins."origins:elytrian"]
		enabled = true
		"origins:elytra" = true
		"origins:launch_into_air" = true
		"origins:aerial_combatant" = true
		"origins:light_armor" = true
		"origins:claustrophobia" = true
		"origins:more_kinetic_damage" = true

	[origins."dragon_origins:green_dragon_origin"]
		enabled = true
		"dragon_origins:good_neighboer" = true
		"dragon_origins:green" = true
		"dragon_origins:elytra" = true
		"dragon_origins:white_teeth" = true
		"dragon_origins:vegie" = true
		"dragon_origins:food" = true
		"dragon_origins:size" = true
		"dragon_origins:emerald" = true
		"dragon_origins:droar" = true

	[origins."dragon_origins:cookie"]
		enabled = true
		"dragon_origins:canibalism" = true
		"dragon_origins:spillage" = true

	[origins."dragon_origins:kraken"]
		enabled = true
		"dragon_origins:kraken/bigger_kraken" = true
		"dragon_origins:kraken/sea_creature" = true
		"dragon_origins:kraken/tentacles" = true
		"dragon_origins:kraken/grapple" = true
		"dragon_origins:kraken/grappledesc" = true
		"dragon_origins:kraken/grappletp" = true
		"origins:air_from_potions" = true
		"origins:aqua_affinity" = true
		"origins:more_exhaustion" = true
		"origins:carnivore" = true
		"origins:water_vision" = true
		"origins:conduit_power_on_land" = true
		"origins:like_water" = true
		"origins:water_breathing" = true

	[origins."dragon_origins:mini"]
		enabled = true
		"dragon_origins:speed" = true
		"dragon_origins:size2" = true
		"origins:fall_immunity" = true
		"origins:climbing" = true
		"dragon_origins:haste" = true
		"origins:no_shield" = true
		"dragon_origins:less_hp" = true
		"dragon_origins:speedswim" = true
		"dragon_origins:speed_boost" = true
		"origins:carnivore" = true
		"dragon_origins:slow" = true
		"dragon_origins:jump_boost" = true

	[origins."origins-classes:explorer"]
		enabled = true
		"origins-classes:explorer_kit" = true
		"origins-classes:no_sprint_exhaustion" = true

	[origins."origins:phantom"]
		enabled = true
		"origins:phantomize" = true
		"origins:translucent" = true
		"origins:phasing" = true
		"origins:invisibility" = true
		"origins:burn_in_daylight" = true
		"origins:hunger_over_time" = true
		"origins:fragile" = true
		"origins:phantomize_overlay" = true

	[origins."dragon_origins:test"]
		enabled = true
		"dragon_origins:test/invis_temp" = true
		"dragon_origins:test/heal" = true
		"dragon_origins:test/lightning" = true
		"dragon_origins:test/dimension" = true

	[origins."origins-classes:beastmaster"]
		enabled = true
		"origins-classes:tamed_animal_boost" = true
		"origins-classes:tamed_potion_diffusal" = true

	[origins."origins-classes:merchant"]
		enabled = true
		"origins-classes:trade_availability" = true
		"origins-classes:rare_wandering_loot" = true

	[origins."origins-classes:rancher"]
		enabled = true
		"origins-classes:twin_breeding" = true
		"origins-classes:more_animal_loot" = true

	[origins."origins:blazeborn"]
		enabled = true
		"origins:fire_immunity" = true
		"origins:nether_spawn" = true
		"origins:burning_wrath" = true
		"origins:hotblooded" = true
		"origins:water_vulnerability" = true
		"origins:flame_particles" = true
		"origins:damage_from_snowballs" = true
		"origins:damage_from_potions" = true

	[origins."origins:avian"]
		enabled = true
		"origins:slow_falling" = true
		"origins:fresh_air" = true
		"origins:like_air" = true
		"origins:tailwind" = true
		"origins:lay_eggs" = true
		"origins:vegetarian" = true

	[origins."origins-classes:archer"]
		enabled = true
		"origins-classes:no_projectile_divergence" = true
		"origins-classes:less_bow_slowdown" = true

	[origins."origins-classes:farmer"]
		enabled = true
		"origins-classes:more_crop_drops" = true
		"origins-classes:better_bone_meal" = true

	[origins."dragon_origins:cyborg"]
		enabled = true
		"dragon_origins:metal_skin" = true
		"dragon_origins:water" = true
		"dragon_origins:xtrajump" = true
		"dragon_origins:fire_immunity" = true
		"dragon_origins:no_armor" = true
		"dragon_origins:fall_dam" = true
		"dragon_origins:night_v" = true

	[origins."origins-classes:miner"]
		enabled = true
		"origins-classes:more_stone_break_speed" = true
		"origins-classes:no_mining_exhaustion" = true

	[origins."dragon_origins:panda"]
		enabled = true
		"dragon_origins:panda/food" = true
		"dragon_origins:panda/food_dis" = true
		"origins:vegetarian" = true

	[origins."dragon_origins:red_dragon"]
		enabled = true
		"origins:fire_immunity" = true
		"origins:nether_spawn" = true
		"origins:burning_wrath" = true
		"origins:water_vulnerability" = true
		"origins:hotblooded" = true

	[origins."dragon_origins:pirate"]
		enabled = true
		"dragon_origins:pirate/hook" = true
		"dragon_origins:pirate/eye_patch" = true
		"dragon_origins:pirate/swim_speed" = true
		"dragon_origins:pirate/home" = true
		"dragon_origins:pirate/shiny" = true

	[origins."origins-classes:cook"]
		enabled = true
		"origins-classes:better_crafted_food" = true
		"origins-classes:more_smoker_xp" = true

	[origins."dragon_origins:druid"]
		enabled = true
		"dragon_origins:f_buf" = true
		"dragon_origins:nether2" = true
		"dragon_origins:hot_debuf" = true
		"dragon_origins:vegie3" = true
		"dragon_origins:roots" = true
		"dragon_origins:roots2" = true
		"dragon_origins:roots3" = true
		"dragon_origins:heal2" = true
		"dragon_origins:regen" = true
		"dragon_origins:plant_v" = true
		"dragon_origins:green2" = true
		"dragon_origins:hunger" = true

	[origins."dragon_origins:yang"]
		enabled = true
		"dragon_origins:yinyang/yang/yintransform" = true
		"dragon_origins:yinyang/yang/cloud" = true
		"dragon_origins:yinyang/yang/posess" = true
		"dragon_origins:yinyang/yang/transparency1" = true
		"dragon_origins:yinyang/yang/dayweak" = true
		"dragon_origins:yinyang/yang/invis_temp" = true

	[origins."origins:human"]
		enabled = true

	[origins."origins-classes:lumberjack"]
		enabled = true
		"origins-classes:tree_felling" = true
		"origins-classes:more_planks_from_logs" = true

	[origins."origins:shulk"]
		enabled = true
		"origins:shulker_inventory" = true
		"origins:natural_armor" = true
		"origins:strong_arms" = true
		"origins:strong_arms_break_speed" = true
		"origins:no_shield" = true
		"origins:more_exhaustion" = true

	[origins."origins-classes:cleric"]
		enabled = true
		"origins-classes:potion_bonus" = true
		"origins-classes:better_enchanting" = true

	[origins."dragon_origins:magic_fly"]
		enabled = true
		"dragon_origins:vegie2" = true
		"dragon_origins:fairy_wings" = true
		"dragon_origins:easy_travel" = true
		"dragon_origins:size3" = true
		"dragon_origins:slow" = true
		"origins:fall_immunity" = true
		"dragon_origins:6hp" = true
		"dragon_origins:no_swords" = true
		"dragon_origins:iron_golem" = true
		"dragon_origins:heal" = true
		"dragon_origins:no_combat" = true
		"dragon_origins:hot_debuf" = true
		"dragon_origins:nether" = true
		"dragon_origins:hunger" = true

	[origins."origins:merling"]
		enabled = true
		"origins:water_breathing" = true
		"origins:water_vision" = true
		"origins:aqua_affinity" = true
		"origins:swim_speed" = true
		"origins:like_water" = true
		"origins:aquatic" = true
		"origins:conduit_power_on_land" = true
		"origins:air_from_potions" = true

	[origins."dragon_origins:undead"]
		enabled = true
		"dragon_origins:zombie" = true
		"dragon_origins:daylight" = true
		"dragon_origins:hugs" = true
		"dragon_origins:body" = true
		"dragon_origins:body_" = true
		"dragon_origins:gloom" = true
		"dragon_origins:undead" = true
		"dragon_origins:unnerving" = true
		"dragon_origins:attacker" = true
		"dragon_origins:target" = true
		"dragon_origins:join_team" = true
		"dragon_origins:create_team" = true
		"dragon_origins:summon" = true
		"dragon_origins:shovel" = true
		"dragon_origins:stone_sword" = true

	[origins."origins:arachnid"]
		enabled = true
		"origins:climbing" = true
		"origins:master_of_webs" = true
		"origins:carnivore" = true
		"origins:fragile" = true
		"origins:arthropod" = true

	[origins."dragon_origins:mimic"]
		enabled = true
		"dragon_origins:mimic/toggle" = true
		"dragon_origins:mimic/toggle2" = true
		"dragon_origins:mimic/display" = true
		"origins:nine_lives" = true

	[origins."dragon_origins:yin"]
		enabled = true
		"dragon_origins:yinyang/yin/yangtransform" = true
		"dragon_origins:yinyang/yin/heal" = true
		"dragon_origins:test/lightning" = true
		"dragon_origins:yinyang/yin/transparency" = true
		"dragon_origins:yinyang/yin/darkweak" = true

	[origins."origins-classes:blacksmith"]
		enabled = true
		"origins-classes:quality_equipment" = true
		"origins-classes:efficient_repairs" = true

	[origins."dragon_origins:necromancer"]
		enabled = true
		"dragon_origins:gloom" = true
		"dragon_origins:gloom2" = true
		"dragon_origins:mysterous" = true
		"dragon_origins:emume" = true
		"dragon_origins:summon/sz_summon" = true
		"dragon_origins:summon/a_summon" = true
		"dragon_origins:summon/d_summon" = true
		"dragon_origins:cloak" = true

	[origins."origins-classes:rogue"]
		enabled = true
		"origins-classes:sneaky" = true
		"origins-classes:stealth" = true
		"origins-classes:stealth_core" = true

	[origins."gaster:gaster"]
		enabled = true
		"gaster:nobody" = true
		"gaster:weak" = true
		"gaster:fall" = true
		"gaster:colision" = true
		"gaster:hunger" = true
		"gaster:regen" = true
		"gaster:phase" = true
		"gaster:immortal" = true
		"gaster:potion" = true
		"gaster:invisible" = true
		"gaster:nope" = true
		"gaster:sprint" = true
		"gaster:teleport" = true
		"gaster:bow" = true
		"gaster:particle" = true
		"gaster:fluid1" = true
		"origins:aqua_affinity" = true
		"origins:cat_vision" = true
		"origins:water_vision" = true

	[origins."wizard:wizard"]
		enabled = true
		"wizard:grimoirecreation" = true
		"wizard:spectralbeam" = true
		"wizard:shadowbeam" = true
		"wizard:leech" = true
		"wizard:hex" = true
		"wizard:remedy" = true
		"wizard:guarding" = true
		"wizard:dart" = true
		"wizard:warp" = true
		"wizard:magic" = true
		"wizard:magicxp" = true
		"wizard:magicimmune" = true
		"wizard:fragilecasting" = true
		"wizard:weak" = true
		"wizard:ineptmagic" = true
		"wizard:ineptall" = true

	[origins."myce:reaper"]
		enabled = true
		"myce:ghostly_form" = true
		"myce:dash2" = true
		"myce:debuff" = true
		"myce:buff" = true
		"myce:no_eat" = true
		"myce:heal" = true
		"myce:nofall" = true
		"myce:grab" = true
		"myce:soul_steal" = true
		"myce:phase_debuff" = true
		"myce:sun" = true
		"myce:fire" = true
		"myce:ghost" = true
		"myce:rip2" = true
		"myce:rip3" = true
		"myce:credits" = true

